#!/usr/bin/env python3
"""Report exact and near-duplicate MOO example bodies."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXAMPLES_DIR = ROOT / "examples"


def main() -> int:
    parser = argparse.ArgumentParser(description="Report duplicate or near-duplicate MOO examples")
    parser.add_argument("--output", type=Path, default=Path("docs/duplicate-example-report.md"), help="Markdown report path")
    parser.add_argument("--json-output", type=Path, help="Optional JSON report path")
    parser.add_argument("--include-all", action="store_true", help="Include singleton families in JSON output")
    args = parser.parse_args()

    rows = collect_rows()
    exact = cluster(rows, "exact_hash")
    family = cluster(rows, "family_hash")
    report = {
        "summary": {
            "examples": len(rows),
            "exact_duplicate_clusters": sum(1 for group in exact.values() if len(group) > 1),
            "family_duplicate_clusters": sum(1 for group in family.values() if len(group) > 1),
        },
        "exact_duplicates": [group for group in exact.values() if len(group) > 1],
        "family_duplicates": [group for group in family.values() if len(group) > 1],
    }

    write_markdown(args.output, report)
    if args.json_output:
        payload = report if not args.include_all else {**report, "all_rows": rows}
        write_json(args.json_output, payload)

    print(
        "Found "
        f"{report['summary']['exact_duplicate_clusters']} exact duplicate cluster(s) and "
        f"{report['summary']['family_duplicate_clusters']} near-family duplicate cluster(s)."
    )
    return 0


def collect_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for path in sorted(EXAMPLES_DIR.rglob("*.moo")):
        text = path.read_text(encoding="utf-8")
        metadata, body = split_example(text)
        normalized = normalize_body(body)
        rows.append(
            {
                "path": path.relative_to(ROOT).as_posix(),
                "title": metadata.get("title", path.stem),
                "topic": metadata.get("topic", "unspecified"),
                "dialect": metadata.get("dialect", "unspecified"),
                "source": metadata.get("source", "unspecified"),
                "exact_hash": hashlib.sha1(normalized.encode("utf-8")).hexdigest(),
                "family_hash": hashlib.sha1(family_normalize(normalized).encode("utf-8")).hexdigest(),
            }
        )
    return rows


def split_example(text: str) -> tuple[dict[str, str], str]:
    metadata: dict[str, str] = {}
    lines = text.splitlines()
    body_start = 0
    for index, line in enumerate(lines):
        if not line.strip():
            body_start = index + 1
            break
        match = re.match(r'^"\s*([a-z_]+):\s*(.*?)";\s*$', line)
        if match:
            metadata[match.group(1)] = match.group(2)
    return metadata, "\n".join(lines[body_start:])


def normalize_body(body: str) -> str:
    code_lines = []
    comment_lines = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith('"'):
            comment_lines.append(stripped)
            continue
        code_lines.append(stripped)
    return "\n".join(code_lines or comment_lines)


def family_normalize(body: str) -> str:
    body = re.sub(r"\b[a-zA-Z_]+_[0-9]+\b", "NAME_N", body)
    body = re.sub(r"\b[0-9]+\b", "N", body)
    body = re.sub(r'"[^"]*"', '"S"', body)
    return body


def cluster(rows: list[dict[str, str]], key: str) -> dict[str, list[dict[str, str]]]:
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[row[key]].append(row)
    return dict(groups)


def write_markdown(raw_path: Path, report: dict[str, object]) -> None:
    path = raw_path if raw_path.is_absolute() else ROOT / raw_path
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Duplicate Example Report",
        "",
        "Generated by `python3 scripts/report_duplicate_examples.py`.",
        "",
        "## Summary",
        "",
        f"- examples: {report['summary']['examples']}",
        f"- exact duplicate clusters: {report['summary']['exact_duplicate_clusters']}",
        f"- near-family duplicate clusters: {report['summary']['family_duplicate_clusters']}",
        "",
        "## Exact Duplicates",
        "",
    ]
    append_groups(lines, report["exact_duplicates"])
    lines.extend(["", "## Near-Family Duplicates", ""])
    append_groups(lines, report["family_duplicates"])
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def append_groups(lines: list[str], groups: object) -> None:
    typed_groups = groups if isinstance(groups, list) else []
    if not typed_groups:
        lines.append("None.")
        return
    for index, group in enumerate(typed_groups, start=1):
        lines.append(f"### Cluster {index}")
        lines.append("")
        for row in group:
            lines.append(f"- `{row['path']}` ({row['topic']}, {row['dialect']}, {row['source']})")
        lines.append("")


def write_json(raw_path: Path, payload: dict[str, object]) -> None:
    path = raw_path if raw_path.is_absolute() else ROOT / raw_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
