#!/usr/bin/env python3
"""Report dataset and eval coverage for planning new training data."""

from __future__ import annotations

import json
import argparse
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[1]
DATASETS_DIR = ROOT / "datasets"
EVALS_DIR = ROOT / "evals"
DOCS_DIR = ROOT / "docs"
EXAMPLE_INDEX_PATH = DATASETS_DIR / "example-index.jsonl"
INSTRUCTION_PATH = DATASETS_DIR / "instruction-examples.jsonl"
CONTRASTIVE_PATH = DATASETS_DIR / "contrastive-examples.jsonl"
DOC_STEMS_WITHOUT_EXAMPLE_TOPICS = {
    "compile-status",
    "coverage-report",
    "curation-queue",
    "curriculum-map",
    "dataset-card",
    "duplicate-example-report",
    "duplicate-policy",
    "eval-coverage-report",
    "generated-expansion-quality-review",
    "near-family-duplicate-review",
    "roadmap",
    "training-canary",
    "training-quality-report",
    "training-recipes",
    "utility-verb-review-summary",
}


def main() -> int:
    parser = argparse.ArgumentParser(description="Report dataset and eval coverage for planning new training data")
    parser.add_argument("--output", type=Path, help="Optional markdown report path")
    args = parser.parse_args()

    ensure_example_index()

    examples = load_jsonl(EXAMPLE_INDEX_PATH)
    instructions = load_jsonl(INSTRUCTION_PATH)
    contrastive = load_jsonl(CONTRASTIVE_PATH)
    eval_files = sorted(EVALS_DIR.rglob("*.jsonl"))
    eval_rows_by_file = {path: load_jsonl(path) for path in eval_files}
    docs = sorted(path for path in DOCS_DIR.rglob("*.md") if path.name != "coverage-report.md")

    lines: list[str] = []
    lines.append("# Coverage Report")
    lines.append("")
    lines.append("Generated by `python3 scripts/report_coverage.py`.")
    lines.append("")
    lines.extend(summary_section(examples, instructions, contrastive, eval_rows_by_file, docs))
    lines.extend(example_sections(examples))
    lines.extend(dataset_sections(instructions, contrastive))
    lines.extend(eval_sections(eval_rows_by_file))
    lines.extend(doc_sections(docs))
    lines.extend(gap_section(examples, instructions, contrastive, eval_rows_by_file, docs))

    report = "\n".join(lines) + "\n"
    if args.output:
        output = args.output if args.output.is_absolute() else ROOT / args.output
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(report, encoding="utf-8")
    else:
        print(report, end="")
    return 0


def ensure_example_index() -> None:
    subprocess.run(
        [sys.executable, "scripts/build_example_index.py"],
        cwd=ROOT,
        check=True,
        stdout=subprocess.DEVNULL,
    )


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip():
            rows.append(json.loads(line))
    return rows


def summary_section(
    examples: list[dict[str, Any]],
    instructions: list[dict[str, Any]],
    contrastive: list[dict[str, Any]],
    eval_rows_by_file: dict[Path, list[dict[str, Any]]],
    docs: list[Path],
) -> list[str]:
    eval_total = sum(len(rows) for rows in eval_rows_by_file.values())
    return [
        "## Summary",
        "",
        markdown_table(
            ["Artifact", "Count"],
            [
                ["examples", len(examples)],
                ["instruction rows", len(instructions)],
                ["contrastive rows", len(contrastive)],
                ["eval rows", eval_total],
                ["docs", len(docs)],
            ],
        ),
        "",
    ]


def example_sections(examples: list[dict[str, Any]]) -> list[str]:
    lines = ["## Examples", ""]
    lines.append(counter_table("By Topic", Counter(row.get("topic", "") for row in examples)))
    lines.append("")
    lines.append(counter_table("By Dialect", Counter(row.get("dialect", "") for row in examples)))
    lines.append("")
    lines.append(counter_table("By Source", Counter(row.get("source", "") for row in examples)))
    lines.append("")
    lines.append(counter_table("By Callable", Counter(row.get("callable", "unspecified") for row in examples)))
    lines.append("")
    return lines


def dataset_sections(instructions: list[dict[str, Any]], contrastive: list[dict[str, Any]]) -> list[str]:
    lines = ["## Datasets", ""]
    lines.append(counter_table("Instruction Rows By Topic", Counter(row.get("topic", "") for row in instructions)))
    lines.append("")
    lines.append(counter_table("Instruction Rows By Dialect", Counter(row.get("dialect", "") for row in instructions)))
    lines.append("")
    lines.append(counter_table("Contrastive Rows By Label", Counter(row.get("label", "") for row in contrastive)))
    lines.append("")
    lines.append(counter_table("Contrastive Rows By Dialect", Counter(row.get("dialect", "") for row in contrastive)))
    lines.append("")
    return lines


def eval_sections(eval_rows_by_file: dict[Path, list[dict[str, Any]]]) -> list[str]:
    lines = ["## Evals", ""]
    file_rows = []
    kind_counter: Counter[str] = Counter()
    dialect_counter: Counter[str] = Counter()
    for path, rows in eval_rows_by_file.items():
        file_rows.append([path.relative_to(ROOT).as_posix(), len(rows)])
        kind_counter.update(row.get("kind", "") for row in rows)
        dialect_counter.update(row.get("dialect", "") for row in rows)
    lines.append(markdown_table(["File", "Rows"], file_rows))
    lines.append("")
    lines.append(counter_table("Eval Rows By Kind", kind_counter))
    lines.append("")
    lines.append(counter_table("Eval Rows By Dialect", dialect_counter))
    lines.append("")
    return lines


def doc_sections(docs: list[Path]) -> list[str]:
    rows = [[path.relative_to(ROOT).as_posix()] for path in docs]
    return [
        "## Docs",
        "",
        markdown_table(["Path"], rows),
        "",
    ]


def gap_section(
    examples: list[dict[str, Any]],
    instructions: list[dict[str, Any]],
    contrastive: list[dict[str, Any]],
    eval_rows_by_file: dict[Path, list[dict[str, Any]]],
    docs: list[Path],
) -> list[str]:
    example_topics = {row.get("topic", "") for row in examples}
    instruction_topics = {row.get("topic", "") for row in instructions}
    eval_file_stems = {path.stem for path in eval_rows_by_file}
    doc_stems = {path.stem for path in docs}

    gaps: list[str] = []
    topics_without_instruction = sorted(topic for topic in example_topics if topic and topic not in instruction_topics)
    if topics_without_instruction:
        gaps.append("Example topics without instruction rows: " + ", ".join(topics_without_instruction))

    docs_without_examples = sorted(
        stem
        for stem in doc_stems
        if stem not in example_topics
        and stem not in {"readme"}
        and stem not in DOC_STEMS_WITHOUT_EXAMPLE_TOPICS
    )
    if docs_without_examples:
        gaps.append("Doc stems without matching example topic: " + ", ".join(docs_without_examples))

    topics_without_named_eval = sorted(topic for topic in example_topics if topic and topic not in eval_file_stems and topic != "repairs")
    if topics_without_named_eval:
        gaps.append("Example topics without same-named eval file: " + ", ".join(topics_without_named_eval))

    if Counter(row.get("topic", "") for row in examples).get("repairs", 0) > len(examples) / 3:
        gaps.append("Repair examples are more than one third of example rows; keep default exports excluding repairs unless training repair behavior.")

    if not contrastive:
        gaps.append("No contrastive rows found.")

    return [
        "## Planning Notes",
        "",
        *[f"- {gap}" for gap in gaps],
        "" if gaps else "- No obvious coverage gaps detected.",
        "",
    ]


def counter_table(title: str, counter: Counter[str]) -> str:
    rows = [[key or "unspecified", count] for key, count in sorted(counter.items(), key=lambda item: (-item[1], item[0]))]
    return "\n".join([f"### {title}", "", markdown_table(["Value", "Count"], rows)])


def markdown_table(headers: list[str], rows: Iterable[Iterable[Any]]) -> str:
    rows = [[str(cell) for cell in row] for row in rows]
    widths = [len(header) for header in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    def fmt(row: Iterable[Any]) -> str:
        cells = [str(cell) for cell in row]
        return "| " + " | ".join(cell.ljust(widths[index]) for index, cell in enumerate(cells)) + " |"

    separator = "| " + " | ".join("-" * width for width in widths) + " |"
    return "\n".join([fmt(headers), separator, *(fmt(row) for row in rows)])


if __name__ == "__main__":
    raise SystemExit(main())
